# Generated by Django 6.1 on 2026-08-17 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority_id', models.IntegerField(primary_key=True, serialize=False)),
                ('priority_name', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_id', models.IntegerField(primary_key=True, serialize=False)),
                ('task_title', models.CharField(max_length=150)),
                ('task_description', models.TextField(max_length=500)),
                ('task_deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress ', 'In Progress'), ('Completed', 'Completed')], default='pending', max_length=50)),
                ('task_priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priority', to='hangarin.priority')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subtask_id', models.IntegerField(primary_key=True, serialize=False)),
                ('subtask_title', models.CharField(max_length=255)),
                ('subtask_status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress ', 'In Progress'), ('Completed', 'Completed')], default='pending', max_length=50)),
                ('parent_task_subtask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='hangarin.task')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note_id', models.IntegerField(primary_key=True, serialize=False)),
                ('note_content', models.TextField(max_length=500)),
                ('parent_task_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='hangarin.task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
