# Generated by Django 6.1 on 2026-08-17 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangarin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='hangarin.category'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='priority', to='hangarin.priority'),
        ),
    ]
